### ISSUE TITLE
Usage w/o atom editor?

### ISSUE THREAD

**Issue by CrazyPython** [Kivifreak/linter-processing#3]

**Comment by bvoq** [comment]
If you install Processing IDE you can install the command line tool processing-java.

You then simply type:
processing-java --sketch=filePath --build

Processing-java saidly only outputs one error at a time (you might want to look into PDE X for that or simply convert it into a java project and run linting on that).
Cheers!

**Comment by CrazyPython** [comment]
@bvoq ...what if I don't want to install processing IDE? :P
